### ISSUE TITLE
UI Web View goes Blank after adding item to list and selecting different color - iOS 9

### ISSUE THREAD

**Issue by trishayy** [IBM-MIL/IBM-Ready-App-for-Retail#10]
Bug only seems to happen in iOS 9.

Steps to reproduce:
1 - add item to any list
2 - pop over view of adding to list goes away
3 - click on a different color for the item
4 - view then goes completely white (see attached image) 
<img width="382" alt="screen shot 2015-10-22 at 4 46 23 pm" src="https://cloud.githubusercontent.com/assets/11196500/10679197/888bf94c-78dc-11e5-8265-1b94a9ea77a0.png">

Doesn't seem to do anything unless you go back to a different view and then click on the item again.

**Comment by jballands** [comment]
Fixed with 3fa4159
