### ISSUE TITLE
Android app cannot install on Amazon Fire

### ISSUE THREAD

**Issue by dfirsht** [IBM-MIL/IBM-Ready-App-for-Retail#12]
I tried to install on an Amazon Fire running Fire OS 3.5.1 and received the message "Parse error: There was a problem parsing the package."

**Comment by kweinmeister** [comment]
Try this: http://stackoverflow.com/questions/8830282/amazon-kindle-fire-and-apk-file

**Comment by ruslan120101** [comment]
@dfirsht status?

**Comment by dfirsht** [comment]
@ruslan120101 This is still an issue, for now we will update the docs to reflect that we will not be supporting Amazon Fiew

**Comment by ruslan120101** [comment]
Fire maybe someday. Not today : /
