### ISSUE TITLE
Memory warning crashes on iOS

### ISSUE THREAD

**Issue by atcabral** [IBM-MIL/IBM-Ready-App-for-Retail#2]
Information from the last 7 days: 
![image](https://cloud.githubusercontent.com/assets/8883443/10062996/5dbb6032-622e-11e5-98cd-22d368f2fb6b.png)

**Comment by atcabral** [comment]
Please check MQA logs for more details. This is the general error I'm seeing "Application was probably terminated by memory warning." Issue seems to be happening across devices and OS levels. 
![image](https://cloud.githubusercontent.com/assets/8883443/10063038/e4216a18-622e-11e5-9058-8385bf30219b.png)

**Comment by atcabral** [comment]
![image](https://cloud.githubusercontent.com/assets/8883443/10171806/9290e8b4-66a1-11e5-87d4-5bd4678e8cc2.png)
Update for this week

**Comment by ruslan120101** [comment]
Numerous bug fixes and cleanups later these issues seem to have abated. If they continue please contact me via IBM email.
