### ISSUE TITLE
Documentation states wrong Xcode version.

### ISSUE THREAD

**Issue by trishayy** [IBM-MIL/IBM-Ready-App-for-Retail#8]
In the docs under the developing iOS tab, it states that you need Xcode version 6.1. 
This needs to be updated to version 6.4.

**Comment by trishayy** [comment]
Needs to be updated to 7.0 now

**Comment by ruslan120101** [comment]
Fixed as of 96e1c2e87825b2c517e85ffd51f440aa9ec75b79 on raDocs
